### ISSUE TITLE
Unable to complete chapter 2 unlock

### ISSUE THREAD

**Issue by autumnfound** [Laskyyy/Create-Astral#117]
Currently playing through the pack, and am unable to finish the chapter 2 unlock using grout. I have a half stack in my inventory which is the needed stack size. I've tried dropping the items and also moving it around to see if there was weirdness in detection but no dice.

I had to use the editor mode, which worked well enough since I'm in in an SP world (details here for anyone who experiences this https://www.reddit.com/r/feedthebeast/comments/g42kvp/ftb_quests_command_to_force_complete_quest/)

Current version: v2.0.4c

**Comment by autumnfound** [comment]
Additionally, a quest in chap. 2 which needs the Seared Melter doesn't seem to complete either.

**Comment by minecraftothersteve** [comment]
You mentioned trying to move the items around, but guessing that means from one inventory slot to another, so thought I'd share my go-to solution that works almost every time: move the items to a chest, close the chest, then grab the items from the chest. I think this has worked almost 100% of the time for me. 
I've not taken the time to look at the code for the quest system, but I'm guessing rather than constantly checking your inventory every tick to see if you have the required items, it's just checking when you interact with a storage blocks. And maybe things like the mixer aren't considered storage blocks. Although you'd think manually crafting the seared melter would trigger it ¯\_(ツ)_/¯

**Comment by Laskyyy** [comment]
I've not been able to replicate this, most workarounds have seemed to allow me to trigger it.
