### ISSUE TITLE
Game crash upon receiving items from using handheld sieve recipes

### ISSUE THREAD

**Issue by FractalOverlord** [Laskyyy/Create-Astral#120]
### Description:
Sifting an item while its corresponding mesh is in your offhand works as expected. However, the game crashes whenever a drop is issued from the sifting recipe.

### Steps to reproduce:
1. Equip a brass mesh to your offhand.
2. Equip any amount of basalt in your main hand.
3. Sift the material using right-click until a drop is issued from the recipe.

### Crash message:
> The game crashed whilst ticking player
> Error: java.lang.NoClassDefFoundError:
> dev/cafeteria/fakeplayerapi/server/FakeServerPlayer

### Crash log:
https://pastebin.com/Fcrw0Lzj

Edit: Moved crash log to pastebin.

**Comment by Erdragh** [comment]
Alright, first things first, please use pastebin, GitHub gists or something similar to post the crash logs, as putting them right in the issue makes them very unreadable.

secondly, what version of the modpack are you on? I remember fake player classes missing being a symptom of create not being updated. We since updated it in the latest version of the pack: 2.0.4c

**Comment by FractalOverlord** [comment]
It seems I was using 2.0.4b. I'll go ahead and update my version.
