### ISSUE TITLE
"Trading has been disabled" and 2 Resource Packs breaking a few textures

### ISSUE THREAD

**Issue by NoobigBoom** [Laskyyy/Create-Astral#148]
Hello! Today I have hopped on some Create Astral and I went to trade my rotten flesh with the village cleric, I have gotten the "Trading has been disabled!" message just above the hotbar. I have not altered the modpack in any way other than adding "Essential" to play in offline LAN but I do not think the issue comes from "Essential", I might be wrong though. Yesterday and the day before yesterday it worked fine trading with them.
There is also an issue that I found while writing this 2 resource packs cause textures to become the black and purple block, mainly for the copper tools.
In the screenshot where the resource packs are shown, the 2 encircled by the red marker are the ones that caused the issue.
![2023-05-18_21 57 44_edited
![2023-05-18_22 04 31_edited](https://github.com/Laskyyy/Create-Astral/assets/134005973/5772e044-7dd1-44d3-8c83-06ff717c5d06)

![2023-05-18_21 26 23_edited](https://github.com/Laskyyy/Create-Astral/assets/134005973/bdc8413a-9956-46ec-8aa6-7769b73e9294)
](https://github.com/Laskyyy/Create-Astral/assets/134005973/c83389e0-b8ef-4d3b-8103-ba6e189e5860)

**Comment by Laskyyy** [comment]
Trading was disabled in 2.0 due to major progression breaks, we've fixed that in the upcoming v2.1 where trading will now be re-enabled by default. (if you want to re enable it yourself without the fixes, just delete the no villager trading mod)

The texture issue is also a rare bug when loading textures through kubejs, it can be fixed by just refreshing textures by pressing f3+t, however I *hope* this shouldnt crop up anymore after rearranging where some of the textures are loaded now in upcoming version.
