### ISSUE TITLE
Create .5.1

### ISSUE THREAD

**Issue by SerinitySW** [Laskyyy/Create-Astral#155]
It would be great to have the new features in create .5.1 such as elevators and the big water wheel

**Comment by Erdragh** [comment]
For this to be possible the following things need to happen:

- Create 0.5.1 needs to be ported to fabric
- all the addons to create we use need to be updated to the new create version
- the new Create content needs to be inserted into our progression in a way that makes sense (e.g. custom crafting recipes)

However, since we're exclusively working on update 2.1 right now, which is at the minimum a few months away, all of the above will probably only be done in connection with update 2.1.

**Comment by dhouck** [comment]
With that timeframe, is 2.1 likely also going to be for 1.20?

**Comment by dhouck** [comment]
… I havenʼt actually played Create Astral; I was planning to set it up soon but hadnʼt gotten to it, and Iʼd misread and thought it was 1.19.2.  Iʼll still play it but good to know going in I got that wrong.  Oops.  At least now I wonʼt be yelling at my server wondering why it isnʼt working, at least not that for that reason.

As for Tech Reborn, it *claims* to go up to 1.19.4 and support 1.19.2; did too much change since 5.2?

**Comment by Erdragh** [comment]
Oh? Tech Reborn updated? Sorry I went off of memory there.

**Comment by Erdragh** [comment]
Anyways, there's other mods that don't support 1.19. 

And there's the issue with Mojangs breaking Change between 1.19.2 and 1.19.4 which has lead to a split in mods that support 1.19

**Comment by DjTeo** [comment]
I am thinking of starting this modpack, should I wait for version 2.1, any info on release date?

oh and now there is Create 0.5.1 Fabric for 1.19.2

**Comment by Erdragh** [comment]
> I am thinking of starting this modpack, should I wait for version 2.1, any info on release date?
> 
> 
> 
> oh and now there is Create 0.5.1 Fabric for 1.19.2

1. we know create 0.5.1 for fabric exists, but not all add ons have been updated yet (for example crafts and additions)
2. there's still lots to do for 2.1 so I'd say start playing now.

**Comment by DjTeo** [comment]
> > I am thinking of starting this modpack, should I wait for version 2.1, any info on release date?
> > oh and now there is Create 0.5.1 Fabric for 1.19.2
> 
> 1. we know create 0.5.1 for fabric exists, but not all add ons have been updated yet (for example crafts and additions)
> 2. there's still lots to do for 2.1 so I'd say start playing now.

Understood, one last question, will the save from 2.0 be compatible with 2.1?

**Comment by Erdragh** [comment]
> will the save from 2.0 be compatible with 2.1?

That's the goal, so yes, but that's not yet certain

**Comment by Erdragh** [comment]
Small update: Create Crafts and Additions has approved a Pull Request updating the 1.18.2 version to create 0.5.1: https://github.com/mrh0/createaddition/pull/593

So for all I know, the only thing missing for an update to 0.5.1 for this modpack is the Create Sifter mod, which will either get updated or we'll have something else replacing it for 2.1.

**Comment by icanc0** [comment]
is the sifter mod open source? it seems to have some bug in it too.

**Comment by Erdragh** [comment]
The forge version is: https://github.com/oierbravo/createsifter

The fabric port isn't. 

We've already pretty much replaced it for 2.1 anyway, so it doesn't really matter.

**Comment by Crazyafk** [comment]
How's it going? excited for this update

**Comment by Erdragh** [comment]
Progress is currently very slow because of real life responsibilities of the dev team members. So far, the recipes were merged into the millstone, but if all goes well, we'll have a replacement made in-House by on of our devs.

**Comment by Erdragh** [comment]
Just to have this information here: 0.5.1 of create is in the `Astral-Experimental` branch and will be in 2.1, as indicated by the label I added in October. The motivation and time issues for the devs haven't been alleviated though, so it will still take some time for 2.1 to release. Keep an eye on our Discord and on this repository for updates.

**Comment by Erdragh** [comment]
2.1 is released
