### ISSUE TITLE
Duplication glitch for v2.0.4c of Create Astral

### ISSUE THREAD

**Issue by ItzJames57** [Laskyyy/Create-Astral#156]
There is an issue with the latest version of the modpack 2.0.4c, where at least on multiplayer servers, there is a duplication glitch where items processed on a belt through either a deployer or press may be duplicated. We think this may be caused by latency, but we are unsure. We know for sure that this problem includes the process of making sturdy sheets (obsidian powder being duped) and basic machine frames (copper casings being duped).

Here is a short video of the problem in question:
https://github.com/Laskyyy/Create-Astral/assets/134802017/71a33138-ef32-4dfa-980b-c7742fe91853

Thanks!

**Comment by ZeekDaGeek** [comment]
Having the same issue with attempting to create Redstone Chips. I put 8 Electron tubes into the input and the belts started jamming, here's the general setup.

![image](https://github.com/Laskyyy/Create-Astral/assets/1709288/cce6b7ee-5ae2-4713-9366-455f8c031805)

As the items passed by the Deployer it would activate twice in quick succession and two items would come out the other side.

**Comment by ZeekDaGeek** [comment]
After comparing both videos and my own setup, it seems like the problem happens when you have a Tech Reborn Storage Unit using the automatic input feature on belts while items are being processed. Moving my Storage Units to a different part of the belt stopped the duplication from happening.

Pulling from the Red squared belt will cause the Blue squared operation to duplicate, and probably happens to any Create Recipe Seque
![gVyRu](https://github.com/Laskyyy/Create-Astral/assets/1709288/212237e7-82db-46e3-aed9-60acdb2df9f4)
nce.

**Comment by Nebby1999** [comment]
Adding to this, i decided to just use a barrel for buffering and chutes, the duplication still  happened, I have a gut feeling the issue is with the mechanical press itself, during creation of circuits with lapiz sheets, i noticed how a single lapis sheet kept duplicating over and over,
![image](https://github.com/Laskyyy/Create-Astral/assets/78170922/063852cd-d229-49db-9a19-57f7ff039510)

**Comment by ItzJames57** [comment]
Has anyone tried lowering/heightening their fps to see if that affects it? I could be like in FNAF Security Breach/Ruin/My Friendly Neighborhood where you can jump up in tight places easier if your game is running at a lower fps. I watch a streamer/speedrunner that goes by AstralSpiff that has done things like that in those games, so maybe its like that...?

**Comment by Sarge889** [comment]
Ive had this exact problem but its for any backed up deployer, starting from even automating andesite casing. i cant just throw a stack of logs and andesite in and let it craft i have to babysit or it dupes and clogs until i interfere. this is making any and all automation extremely annoying because this seems to happen any time i use a deployer in sequence crafting. would anyone happen to have any recommendations on how to fix this? the modpack is currently unplayable for me because of this and its honestly my favorite out of all the ones ive tried so far.

**Comment by Erdragh** [comment]
> this seems to happen any time i use a deployer in sequence crafting.

That is not entirely correct. From what we've been able to gather so far, it's caused by the Crude Storage Unit from Tech Reborn. It's somewhat buggy and when connected to belts directly it can and will break sequences. Never use CSUs directly on belts, always put a buffer chest/barrel with a funnel inbetween.

**Comment by Nebby1999** [comment]
> > this seems to happen any time i use a deployer in sequence crafting.
> 
> That is not entirely correct. From what we've been able to gather so far, it's caused by the Crude Storage Unit from Tech Reborn. It's somewhat buggy and when connected to belts directly it can and will break sequences. Never use CSUs directly on belts, always put a buffer chest/barrel with a funnel inbetween.

This is not true, even on a setup with no crude storage unit whatsoever this happens

**Comment by Erdragh** [comment]
Can you provide a video/instructions on how to reproduce the issue?

**Comment by Sarge889** [comment]
For myself it seems to happen any time i back-up a belt in the sequence crafter, and happens reguardless of the storage units being directly part of the set-up or not, im not sure if this is an extremely unique instance but ive tried re-installing and verifying files. doesnt seem to work, ill try to reproduce it again without the storage units when i have the chance to launch the game to verify

**Comment by TheAndroidx1** [comment]
I have found that this issue specifically happens when a storage unit is pulling at the end of a line, when a unit is pushing from the beginning of a line there is no duping, but if a storage unit is pulling from the line after the deployers/presses it causes them to activate twice duping the result.
I managed to mitigate it by using a funnel to a chest at the end of the assembly line

**Comment by Laskyyy** [comment]
I can reproduce this in 2.0.5 but not in experimental with create 0.5.1 so I *assume* the create team have sorted this in their own pipeline at some point. Hopefully it's sorted, if someone finds a variation after the update i'll need to try and recreate it again.
