### ISSUE TITLE
Can't pick up bronze chest with content

### ISSUE THREAD

**Issue by 3941** [Laskyyy/Create-Astral#180]
So, I just started settling down just to find that all caves in my area seem to be flooded (no ocean in sight, but I'm next to a river).
So I thought I'd move, but I can't pick up bronze chests with ANY wrench. I cheated them all in, just to try, after making the one mentioned in the Copper Chest quest from the little resources I had. No luck.

Are they even supposed to be able to be picked up? Asking because same mod author also makes Reinforced Shulker Boxes.
If not, I guess it's just the quest text that needs fixing.

Version is 2.0.4, installed with Curseforge.

**Comment by ZZZank** [comment]
Well, Copper Chest is 'regular' chest. This means that it is usually not supposed to hold contents when broken whether through wrench or not. 

As for the quest description, I think it is a bug, because it say 'Storage Unit', which is another kind of storage block. 

Also, the feature of wrenching a chest is 'not yet implemented'. Such feature usually require sepcial KubeJS scripts, which is non existent right now. 
Maybe I will start a PR implementing this?

**Comment by Erdragh** [comment]
Where exactly in the quest book is the erroneous text you're referring to?

**Comment by 3941** [comment]
Right here on the first page: https://i.imgur.com/9QJtOsN.jpeg

It does indeed say Storage Unit, and I see that you actually get the wrench if you do the Storage Unit quest. 
So I guess it's a mix up. https://i.imgur.com/StPuQpd.jpeg

**Comment by Erdragh** [comment]
Alright, then this issue will be closed
