### ISSUE TITLE
So I'm running into a problem trying to add a mod to Create Astral and was hoping for some advice on to fix it, If possible

### ISSUE THREAD

**Issue by Heardtube80** [Laskyyy/Create-Astral#240]
All this for about the 1.18.2
So the error code I get is [Internal Exception java.lang.RuntimeException: Sneakythrows]

The mod I'm trying to add in question is MCA Reborn [Fabric/Forge] [https://www.curseforge.com/minecraft/mc-mods/minecraft-comes-alive-reborn]
Which it also adds Architectury [https://www.curseforge.com/minecraft/mc-mods/architectury-api/files]
I added them through curseforge's feature but ran into that error at the top.

I know near to nothing about how mods mingle with one another so any infomation about this whole ordeal would be lovely.

**Comment by Erdragh** [comment]
Please provide a full crash log

**Comment by Heardtube80** [comment]
I got a Log I believe it is tied to it, but I have zero clue if this is what you need, Not good with folder nav. I took a picture of what I see whenever I try and log into a world. The world is bulit fine but I just can't enter it from the looks of it.
[2023-10-20-6.log.gz](https://github.com/Laskyyy/Create-Astral/files/13104260/2023-10-20-6.log.gz)
![image](https://github.com/Laskyyy/Create-Astral/assets/148597870/1e34103c-d5c2-4416-a2ed-d7da246ece16)

**Comment by Erdragh** [comment]
Minecraft Comes Alive is one of the mods affected by the Bleeding Pipe exploit: https://github.com/dogboy21/serializationisbad/blob/master/docs/mods.md

This exception occurs because we include the pipe blocker mod, which prevents the vulnerability from being exploited by blocking code that is vulnerable. You can find more info about the vulnerability and maybe even how to fix MCA on the Repo linked above. This is not an issue with our modpack, as such I will close this issue.
