### ISSUE TITLE
Launching offline seems to hang

### ISSUE THREAD

**Issue by TheAndroidx1** [Laskyyy/Create-Astral#283]
I'm using prism MC on my deck and PC, It loads fast when launching with an internet connection, however it seems to hang when I try to launch offline (which is only possible with an paid copy of Minecraft).
the log hangs on `[main/INFO]: I used the json to destroy the json`
then continues on `[main/WARN]: Failed to load online filter, using local version`

This does not happen with other modpacks so it has to be this modpack, if this is something you cant fix for everyone is there something I can remove that's waiting for a response over the internet?

**Comment by TheAndroidx1** [comment]
[log.txt](https://github.com/Laskyyy/Create-Astral/files/14729426/log.txt)
This is the log if you need it
There was a 20 min wait between the two quotes above

**Comment by Erdragh** [comment]
Ok, this is good to know. We include the pipeblocker mod to prevent a certain type of vulnerability in mods being exploited. This *shouldn't* be necessary anymore as of the last update of the modpack, because the one known vulnerable mod was updated to fix the issue, but we left it in because it *so far* didn't hurt anything. You can remove the mod and it should fix this specific issue. Please update/close this issue if that fixes your issue.

**Comment by TheAndroidx1** [comment]
Thanks a lot, removing pipeblocker allowed it to start immediately!
