### ISSUE TITLE
Server crashing

### ISSUE THREAD

**Issue by PawloZiom** [Laskyyy/Create-Astral#322]
I've installed the newest server pack. I did what the .txt file said and started the server. First it gave me an error about the memoryleakfix mod, i tried deleting it and it worked but then i got second error: 
`[16:01:27] [main/ERROR]: Failed to start the minecraft server
java.lang.RuntimeException: Could not execute entrypoint stage 'main' due to errors, provided by 'automobility'! ...` 
I don't know what to do, this is [latest.log](https://github.com/user-attachments/files/16041352/latest.log).

**Comment by Erdragh** [comment]
You didn't do _exactly_ what the two text files instruct you to do. The text files specify a version for the fabric loader. The currently released version of the modpack is not compatible with fabric 0.15.*, in part because of the memory leak fix mod.

Downgrade fabric loader to at max 0.14.25 and it should work, memoryleakfix included.

**Comment by PawloZiom** [comment]
Thank you! I didn't notice this second file called readme.txt.
