### ISSUE TITLE
[Bug]: content observers delete melter contents

### ISSUE THREAD

**Issue by whatzittuuyah** [Laskyyy/Create-Astral#326]
### Bug Description

A content observer that is observing a melter will cause any item it can detect (ie anything not filtered out) to just vanish as soon as it enters the melter.

### How to Reproduce?

1. Place a seared melter on any block that will allow it to function. It doesn't need fuel
2. place a content observer beside it "looking in"
3. put anything inside by any means

### Expected Behavior

Nothing vanishes from the melter, the content observer simply activates when it detects a valid target and deactivates when there is none. Content observer should fail inertly, rather than interfering with observed container's contents

### Version

2.0.5

### Code of Conduct

- [X] I have searched the issue tracker and confirmed that the issue has not been reported
- [X] I have checked the FAQ (if one is present) and my issue is not listed
- [X] I have verified that I am using the latest version of the modpack
- [X] I have verified that I have followed the required steps to set up the modpack

**Comment by Erdragh** [comment]
Can confirm in 2.0.5b

![2024-07-06_12 08 21](https://github.com/Laskyyy/Create-Astral/assets/29674493/66e5eec1-0053-4c58-ad31-0314749c5610)

If I understand this issue report correctly, the above image should verify that it is fixed, correct? If that's the case a Create update fixed it. The current public release of the modpack is on an outdated version of Create and, *importantly*, cannot be easily updated to a newer Create version. The next update of the modpack will include an updated Create version. As such, I will close this issue as Fixed in 2.1.
